WITH CUSTOMERORDER AS (
    SELECT C.CUSTOMERID,
           CONCAT(C.FIRSTNAME, ' ', C.LASTNAME) AS CUSTOMERNAME,
           COUNT(O.ORDERID) AS ORDERCOUNT
    FROM L1_LANDING.CUSTOMERS C
        JOIN L1_LANDING.ORDERS O ON C.CUSTOMERID = O.CUSTOMERID
    GROUP BY C.CUSTOMERID, CUSTOMERNAME
    ORDER BY ORDERCOUNT DESC
)

SELECT CUSTOMERID, CUSTOMERNAME, ORDERCOUNT
FROM CUSTOMERORDER