sources:
  - name: landing
    description: The primary source system for order management system(OMS) data analytics.
    schema: L1_LANDING
    config:
      freshness:
        warn_after: {count: 1, period: day}
        error_after: {count: 3, period: day}
    loaded_at_field: Updated_at

    tables:
      - name: CUSTOMERS
        description: The customers table from order management system(OMS).
        identifier: CUSTOMERS
      - name: ORDERS
        description: The orders table from order management system(OMS).
        identifier: ORDERS
      - name: ORDERITEMS
        description: The orderitems table from order management system(OMS).
        identifier: ORDERITEMS
      - name: EMPLOYEES
        description: The employees table from order management system(OMS).
        identifier: EMPLOYEES
        columns:
          - name: ADDRESS
            description: Full Address of emplyees for Transport Arrangements.
            tests:
              - not_null
              - string_not_empty
      - name: SALES_US
      - name: SALES_EUROPE
      - name: SALES_ASIA
      - name: STORES
      - name: SUPPLIERS
      - name: PRODUCTS

  - name: TRAINING
    schema: TRAINING
    tables:
      - name: CITY_TEMPERATURE
      - name: sales_us
      - name: sales_uk
      - name: sales_india